name: Lint

on: [push]

jobs:
  golangci:
    strategy:
      matrix:
        go: [1.17]
        os: [macos-latest, windows-latest]

    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.29