name: Lint

on: [push]

jobs:
  gofmt:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Lining code 
        run: gofmt -w ./..

      - name: Lint check
        uses: Jerome1337/gofmt-action@v1.0.5
