name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Test
      run: go test ./...
